# Generated by Django 6.1 on 2026-09-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_projects_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='category',
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='skills',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
