# Generated by Django 6.1 on 2026-09-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_education_category_alter_projects_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='kesan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
